apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memory

resources:
- namespace.yaml
- m1-no-requests-no-limits.yaml
- m2-requests-no-limits.yaml
- m3-requests-and-limits.yaml

commonLabels:
  app.kubernetes.io/part-of: memory-demo
