---
apiVersion: v1
kind: Service
metadata:
  name: requests-and-limits
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: requests-and-limits
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3-requests-and-limits
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: requests-and-limits
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: requests-and-limits
        name: requests-and-limits
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: memory-consumer
        image: reidmv/startup-memory-consumer:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        env:
        - name: STARTUP_CONSUME_MEBIBYTES
          value: "125"
        - name: STARTUP_CONSUME_SECONDS
          value: "0"
        - name: RUNTIME_CONSUME_MEBIBYTES
          value: "130"
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 100m
            memory: 250Mi
