apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
data:
  prometheus.yml: |
    global:
      scrape_interval: 20s
      scrape_timeout: 10s
    scrape_configs:
    - job_name: 'external-cadvisor'
      scrape_interval: "1s"
      scrape_timeout: "1s"
      honor_timestamps: true
      static_configs:
      - targets:
        - cadvisor.monitoring.svc.cluster.local:8080

      metric_relabel_configs:
      # Limit input to only these metrics
      - action: keep
        regex: ^(container_last_seen)|(container_cpu_usage_seconds_total)|(container_cpu_cfs_periods_total)|(container_cpu_cfs_throttled_periods_total)|(container_cpu_cfs_throttled_seconds_total)|(container_memory_working_set_bytes)|(container_memory_max_usage_bytes)$
        source_labels: [ __name__ ]
      - action: replace
        source_labels: [container_label_io_kubernetes_pod_name]
        regex: (.+)
        target_label: pod_name
      - action: replace
        source_labels: [container_label_io_kubernetes_pod_namespace]
        regex: (.+)
        target_label: namespace
      - action: replace
        source_labels: [container_label_io_kubernetes_container_name]
        regex: (.+)
        target_label: container_name
      
      # Add a joinable pod_root_id label to tie the root container cgroup sums 
      # (no pod name label) to metrics that have a pod name label
      - action: replace
        source_labels: [id]
        regex: "(/kubepods[.]slice.*[.]slice).*"
        target_label: pod_root_id
        replacement: "$1"

      # Create a friendly workload name label for demos
      - action: replace
        source_labels: [ pod_name ]
        regex: "^([cm][0-9]*-)?(.+)-[^-]{6,12}-[^-]{4,6}"
        target_label: workload_name
        replacement: "$2"

      # That contain a 'container' label
      #- source_labels: [ container ]
      #  regex: (POD)|
      #  action: drop
      # That contain a 'pod' label
      #- source_labels: [ pod ]
      #  regex: |
      #  action: drop
      # That contain a 'image' label
      #- source_labels: [ image ]
      #  regex: |
      #  action: drop
      # That contain a 'name' label
      #- source_labels: [ name ]
      #  regex: |
      #  action: drop
      # And keep these labels
      #- regex: ^(__name__|cluster_name|container|container_name|instance|name|kubernetes_io_arch|node_kubernetes_io_instance_type|pod|pod_name|topology_kubernetes_io_region|topology_kubernetes_io_zone|workload_name|workload_namespace|workload_resource|namespace|job)$
      #  action: labelkeep
