apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prometheus-server
  name: prometheus-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-server
    spec:
      serviceAccountName: prometheus-server
      containers:
        - name: prometheus-server
          image: "quay.io/prometheus/prometheus:v2.50.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --storage.tsdb.retention.time=1d
            - --config.file=/etc/config/prometheus.yml
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
            - --web.enable-admin-api
          resources:
            requests:
              cpu: 130m
              memory: 256Mi
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server
