apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus-server
