apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests
  namespace: policies
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 250m
      memory: 1Gi
    default:
      cpu: 1000m
      memory: 4Gi
