---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workload
  namespace: policies
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: test-workload
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-workload
        name: test-workload
    spec:
      containers:
      - name: main
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: 400m
            memory: 128Mi
