---
apiVersion: v1
kind: Service
metadata:
  name: small-requests-no-limits
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: small-requests-no-limits
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c3-small-requests-no-limits
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: small-requests-no-limits
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: small-requests-no-limits
        name: small-requests-no-limits
    spec:
      containers:
      - name: resource-consumer
        image: gcr.io/k8s-staging-e2e-test-images/resource-consumer:1.13
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
