apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hpa-cpu-demo

resources:
- namespace.yaml
- c1-no-requests-no-limits.yaml
- c2-requests-no-limits.yaml

commonLabels:
  app.kubernetes.io/part-of: hpa-cpu-demo
