apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.12
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests: 
            memory: 500Mi
            cpu: "100m"
        env:
          - name: GF_PATHS_CONFIG
            value: /var/lib/grafana/custom-ini/custom.ini
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards
            name: grafana-dashboard-provisioners
            readOnly: false
          - mountPath: /var/lib/grafana/dashboards
            name: grafana-dashboards
            readOnly: false
          - mountPath: /var/lib/grafana/custom-ini
            name: grafana-custom-ini
            readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - name: grafana-dashboard-provisioners
          configMap:
            defaultMode: 420
            name: grafana-dashboard-provisioners
        - name: grafana-dashboards
          configMap:
            defaultMode: 420
            name: grafana-dashboards
        - name: grafana-custom-ini
          configMap:
            defaultMode: 420
            name: grafana-custom-ini
