apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: resource-workshop
  region: us-east-1
  version: "1.27"

managedNodeGroups:
- name: ng-1
  instanceType: m5.large
  desiredCapacity: 1

iam:
  withOIDC: true

availabilityZones:
- us-east-1a
- us-east-1b
- us-east-1c
